
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import com.sun.glass.events.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class StaffLogin extends javax.swing.JFrame {
    private String Query;

    /** Creates new form StaffLogin */
    public StaffLogin() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        usernameField.setText("101");
        passwordField.setText("101");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        createUser = new javax.swing.JLabel();
        forgetPassword = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1024, 1024));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-470, 0, 0, 0);

        kGradientPanel1.setBackground(java.awt.Color.cyan);
        kGradientPanel1.setFocusTraversalPolicyProvider(true);
        kGradientPanel1.setkEndColor(new java.awt.Color(21, 153, 87));
        kGradientPanel1.setkStartColor(new java.awt.Color(21, 87, 153));
        kGradientPanel1.setLayout(null);

        jPanel1.setBackground(new Color(1.0f,1.0f,1.0f,0.7f));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16)), "Staff Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 48), new java.awt.Color(102, 51, 0))); // NOI18N
        jPanel1.setLayout(null);

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameField.setText("101");
        usernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(usernameField);
        usernameField.setBounds(140, 80, 350, 30);

        passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordField);
        passwordField.setBounds(140, 150, 350, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel4.setText("Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 80, 100, 40);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 140, 90, 55);

        loginButton.setBackground(new java.awt.Color(0, 153, 204));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LOGIN");
        loginButton.setToolTipText("Press This for next");
        loginButton.setAlignmentY(0.0F);
        loginButton.setAutoscrolls(true);
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 102), 0, true));
        loginButton.setRequestFocusEnabled(false);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginButtonKeyPressed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(30, 240, 470, 60);

        createUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createUser.setForeground(new java.awt.Color(0, 51, 255));
        createUser.setText("Create User");
        createUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUserMouseClicked(evt);
            }
        });
        jPanel1.add(createUser);
        createUser.setBounds(390, 330, 110, 20);

        forgetPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        forgetPassword.setForeground(new java.awt.Color(0, 51, 255));
        forgetPassword.setText("Forgot Password?");
        forgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(forgetPassword);
        forgetPassword.setBounds(30, 330, 140, 22);

        kGradientPanel1.add(jPanel1);
        jPanel1.setBounds(340, 370, 530, 380);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resort.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(100, 40, 1960, 1370);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(-100, -40, 2160, 1380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswordMouseClicked
        forgot forgetPasswordView = new forgot();
        forgetPasswordView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_forgetPasswordMouseClicked

    private void createUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserMouseClicked
        Register registerUserView = new Register();
        registerUserView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createUserMouseClicked

    private void loginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonKeyPressed

    }//GEN-LAST:event_loginButtonKeyPressed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameField.getText();
        String password = new String (passwordField.getPassword());
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn;
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rms", "root", "");
            String query = "SELECT * FROM staff WHERE id='"+username+"' AND password='"+password+"';";
            Statement stmt = (Statement) conn.createStatement();
            ResultSet resultSet = stmt.executeQuery(query);
            if(resultSet.next())
            {
                Welcome2 object=new Welcome2();
                object.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Username or Password!");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonMouseClicked

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StaffLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createUser;
    private javax.swing.JLabel forgetPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
